# Site settings
title: Steven Reynolds
blogtitle: /blog
email: work@stevenreynolds.com
description: > # this means to ignore newlines until "baseurl:"
  Steven is a front end developer and designer in California.
  He explains technical things here. Husband, dad, and cat dad.
url: "http://stevenreynolds.me" # the base hostname & protocol for your site
twitter_username:   stvnrynlds
github_username:    stvnrynlds
dribbble_username:  stevenreynolds

# Build settings
markdown: kramdown
highlighter: rouge

# Sass Settings
sass:
   sass_dir: css/_sass

# Blog Settings
permalink: /blog/:title/