# Site settings
title: /blog
email: work@stevenreynolds.com
description: > # this means to ignore newlines until "baseurl:"
  /blog is by Steven Reynolds, a designer and developer in California. Husband to Amanda, dad to my twins, intern to my cats.
url: "http://stevenreynolds.me" # the base hostname & protocol for your site
twitter_username: stvnrynlds
github_username:  stvnrynlds

# Build settings
markdown: kramdown
highlighter: rouge

# Sass Settings
sass:
   sass_dir: css/_sass